# channel
channel_type: 'MIMO' # Channel mechanism_type values: ['SISO','MIMO'].
channel_model: 'DistortedMIMO' # Physical channel models: ['DistortedMIMO','Synthetic']
detector_type: 'model' # 'model' or 'black_box'
linear: True # channel linearity. Boolean value.
fading_in_channel: False # If the channel is fading/non-fading. values: [True, False]
snr: 12 # validation SNR value. values: float.

# protocol
block_length: 10000 # coherence block time, total size of pilot + data. values: int.
pilot_size: 1000 # pilot bits
blocks_num: 100 # number of validation frames. values: int.

# online training hyperparameters
loss_type: 'CrossEntropy' # Loss mechanism_type. values: 'BCE','CrossEntropy','MSE'.
optimizer_type: 'Adam' # Optimizer mechanism_type. values: 'Adam','RMSprop','SGD'.
seed: 100 # run seed

# concept drift mechanism
mechanism: PERIODIC # ['ALWAYS','DRIFT','PERIODIC']
modular: False
period: 10
drift_detection_method: 'DDM' # ['DDM','PHT','HT','PST']
drift_detection_method_hp: { 'alpha_ddm': 3, 'beta_ddm': 0.2,
                             'beta_pht': 0.5, 'delta_pht': 0.8, 'lambda_pht': 0.01,
                             'ht_threshold': 6, 'posterior_threshold': 0.03 }